In [2]:
import pandas as pd
import numpy as np

In [7]:
data = pd.read_csv("/Users/admin/Desktop/infertility/open (1)/train.csv")
print(f"{data.shape}")

# 모든 컬럼을 다 보이게 설정
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

data.head()

(256351, 69)

             ID 시술 시기 코드 시술 당시 나이  임신 시도 또는 마지막 임신 경과 연수 시술 유형 특정 시술 유형  배란 자극 여부    배란 유도 유형  단일 배아 이식 여부  착상 전 유전 검사 사용 여부  착상 전 유전 진단 사용 여부  남성 주 불임 원인  남성 부 불임 원인  여성 주 불임 원인  여성 부 불임 원인  부부 주 불임 원인  부부 부 불임 원인  불명확 불임 원인  불임 원인 - 난관 질환  불임 원인 - 남성 요인  불임 원인 - 배란 장애  불임 원인 - 여성 요인  불임 원인 - 자궁경부 문제  불임 원인 - 자궁내막증  불임 원인 - 정자 농도  불임 원인 - 정자 면역학적 요인  불임 원인 - 정자 운동성  불임 원인 - 정자 형태 배아 생성 주요 이유 총 시술 횟수 클리닉 내 총 시술 횟수 IVF 시술 횟수 DI 시술 횟수 총 임신 횟수 IVF 임신 횟수 DI 임신 횟수 총 출산 횟수 IVF 출산 횟수 DI 출산 횟수  총 생성 배아 수  미세주입된 난자 수  미세주입에서 생성된 배아 수  이식된 배아 수  미세주입 배아 이식 수  저장된 배아 수  미세주입 후 저장된 배아 수  해동된 배아 수  해동 난자 수  수집된 신선 난자 수  저장된 신선 난자 수  혼합된 난자 수  파트너 정자와 혼합된 난자 수  기증자 정자와 혼합된 난자 수  난자 출처   정자 출처 난자 기증자 나이 정자 기증자 나이  동결 배아 사용 여부  신선 배아 사용 여부  기증 배아 사용 여부  대리모 여부  PGD 시술 여부  PGS 시술 여부  난자 채취 경과일  난자 해동 경과일  난자 혼합 경과일  배아 이식 경과일  배아 해동 경과일  임신 성공 여부
0  TRAIN_000000   TRZKPL  만18-34세                    NaN   IVF     ICSI         1  기록되지 않은 시행          0.0               NaN               0.0           0           0           0           0           0           0          0              0              1              1              0                0              0              0                   0               0              0      현재 시술용      0회            0회        0회       0회      0회        0회       0회      0회        0회       0회        4.0         5.0              4.0       2.0           2.0       2.0              2.0       0.0      0.0          7.0          0.0       5.0               5.0               0.0  본인 제공  배우자 제공    알 수 없음    알 수 없음          0.0          1.0          0.0     0.0        NaN        NaN        0.0        NaN        0.0        3.0        NaN         0
1  TRAIN_000001   TRYBLT  만45-50세                    NaN   IVF     ICSI         0      알 수 없음          0.0               NaN               0.0           0           0           0           0           0           0          0              0              0              0              0                0              0              0                   0               0              0      현재 시술용      0회            0회        0회       0회      0회        0회       0회      0회        0회       0회        0.0         1.0              0.0       0.0           0.0       0.0              0.0       0.0      0.0          1.0          0.0       1.0               1.0               0.0  본인 제공  배우자 제공    알 수 없음    알 수 없음          0.0          1.0          0.0     0.0        NaN        NaN        0.0        NaN        0.0        NaN        NaN         0
2  TRAIN_000002   TRVNRY  만18-34세                    NaN   IVF      IVF         1  기록되지 않은 시행          0.0               NaN               0.0           0           0           0           0           0           0          0              0              1              0              0                0              0              0                   0               0              0      현재 시술용      1회            0회        1회       0회      0회        0회       0회      0회        0회       0회        5.0         0.0              0.0       2.0           0.0       0.0              0.0       0.0      0.0          8.0          0.0       7.0               7.0               0.0  본인 제공  배우자 제공    알 수 없음    알 수 없음          0.0          1.0          0.0     0.0        NaN        NaN        0.0        NaN        0.0        2.0        NaN         0
3  TRAIN_000003   TRJXFG  만35-37세                    NaN   IVF     ICSI         1  기록되지 않은 시행          0.0               NaN               0.0           0           0           0           0           0           0          0              0              1              0              0                0              0              0                   0               0              0      현재 시술용      1회            1회        1회       0회      0회        0회       0회      0회        0회       0회        0.0         4.0              0.0       0.0           0.0       0.0              0.0       0.0      0.0          5.0          0.0       4.0               4.0               0.0  본인 제공  배우자 제공    알 수 없음    알 수 없음          0.0          1.0          0.0     0.0        NaN        NaN        0.0        NaN        0.0        NaN        NaN         0
4  TRAIN_000004   TRVNRY  만18-34세                    NaN   IVF     ICSI         1  기록되지 않은 시행          0.0               NaN               0.0           0           0           0           0           0           0          0              1              0              0              0                0              1              0                   0               0              0      현재 시술용      0회            0회        0회       0회      0회        0회       0회      0회        0회       0회        6.0         6.0              6.0       2.0           2.0       0.0              0.0       0.0      0.0          7.0          0.0       6.0               6.0               0.0  본인 제공  배우자 제공    알 수 없음    알 수 없음          0.0          1.0          0.0     0.0        NaN        NaN        0.0        NaN        0.0        3.0        NaN         0

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256351 entries, 0 to 256350
Data columns (total 69 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   ID                     256351 non-null  object
 1   시술 시기 코드               256351 non-null  object
 2   시술 당시 나이               256351 non-null  object
 3   임신 시도 또는 마지막 임신 경과 연수  9370 non-null    float64
 4   시술 유형                  256351 non-null  object
 5   특정 시술 유형               256349 non-null  object
 6   배란 자극 여부               256351 non-null  int64
 7   배란 유도 유형               256351 non-null  object
 8   단일 배아 이식 여부            250060 non-null  float64
 9   착상 전 유전 검사 사용 여부       2718 non-null    float64
 10  착상 전 유전 진단 사용 여부       250060 non-null  float64
 11  남성 주 불임 원인             256351 non-null  int64
 12  남성 부 불임 원인             256351 non-null  int64
 13  여성 주 불임 원인             256351 non-null  int64
 14  여성 부 불임 원인             256351 non-null  int64
 15  부부 주 불임 원인             256351 non-null  int64
 16  부부 부 불임 원인             256351 non-null  int64
 17  불명확 불임 원인              256351 non-null  int64
 18  불임 원인 - 난관 질환          256351 non-null  int64
 19  불임 원인 - 남성 요인          256351 non-null  int64
 20  불임 원인 - 배란 장애          256351 non-null  int64
 21  불임 원인 - 여성 요인          256351 non-null  int64
 22  불임 원인 - 자궁경부 문제        256351 non-null  int64
 23  불임 원인 - 자궁내막증          256351 non-null  int64
 24  불임 원인 - 정자 농도          256351 non-null  int64
 25  불임 원인 - 정자 면역학적 요인     256351 non-null  int64
 26  불임 원인 - 정자 운동성         256351 non-null  int64
 27  불임 원인 - 정자 형태          256351 non-null  int64
 28  배아 생성 주요 이유            250060 non-null  object
 29  총 시술 횟수                256351 non-null  object
 30  클리닉 내 총 시술 횟수          256351 non-null  object
 31  IVF 시술 횟수              256351 non-null  object
 32  DI 시술 횟수               256351 non-null  object
 33  총 임신 횟수                256351 non-null  object
 34  IVF 임신 횟수              256351 non-null  object
 35  DI 임신 횟수               256351 non-null  object
 36  총 출산 횟수                256351 non-null  object
 37  IVF 출산 횟수              256351 non-null  object
 38  DI 출산 횟수               256351 non-null  object
 39  총 생성 배아 수              250060 non-null  float64
 40  미세주입된 난자 수             250060 non-null  float64
 41  미세주입에서 생성된 배아 수        250060 non-null  float64
 42  이식된 배아 수               250060 non-null  float64
 43  미세주입 배아 이식 수           250060 non-null  float64
 44  저장된 배아 수               250060 non-null  float64
 45  미세주입 후 저장된 배아 수        250060 non-null  float64
 46  해동된 배아 수               250060 non-null  float64
 47  해동 난자 수                250060 non-null  float64
 48  수집된 신선 난자 수            250060 non-null  float64
 49  저장된 신선 난자 수            250060 non-null  float64
 50  혼합된 난자 수               250060 non-null  float64
 51  파트너 정자와 혼합된 난자 수       250060 non-null  float64
 52  기증자 정자와 혼합된 난자 수       250060 non-null  float64
 53  난자 출처                  256351 non-null  object
 54  정자 출처                  256351 non-null  object
 55  난자 기증자 나이              256351 non-null  object
 56  정자 기증자 나이              256351 non-null  object
 57  동결 배아 사용 여부            250060 non-null  float64
 58  신선 배아 사용 여부            250060 non-null  float64
 59  기증 배아 사용 여부            250060 non-null  float64
 60  대리모 여부                 250060 non-null  float64
 61  PGD 시술 여부              2179 non-null    float64
 62  PGS 시술 여부              1929 non-null    float64
 63  난자 채취 경과일              198863 non-null  float64
 64  난자 해동 경과일              1436 non-null    float64
 65  난자 혼합 경과일              202616 non-null  float64
 66  배아 이식 경과일              212785 non-null  float64
 67  배아 해동 경과일              40369 non-null   float64
 68  임신 성공 여부               256351 non-null  int64
dtypes: float64(29), int64(19), object(21)
memory usage: 135.0+ MB

In [11]:
data.describe(include='all')

                  ID 시술 시기 코드 시술 당시 나이  임신 시도 또는 마지막 임신 경과 연수   시술 유형 특정 시술 유형       배란 자극 여부    배란 유도 유형    단일 배아 이식 여부  착상 전 유전 검사 사용 여부  착상 전 유전 진단 사용 여부     남성 주 불임 원인     남성 부 불임 원인     여성 주 불임 원인     여성 부 불임 원인     부부 주 불임 원인     부부 부 불임 원인      불명확 불임 원인  불임 원인 - 난관 질환  불임 원인 - 남성 요인  불임 원인 - 배란 장애  불임 원인 - 여성 요인  불임 원인 - 자궁경부 문제  불임 원인 - 자궁내막증  불임 원인 - 정자 농도  불임 원인 - 정자 면역학적 요인  불임 원인 - 정자 운동성  불임 원인 - 정자 형태 배아 생성 주요 이유 총 시술 횟수 클리닉 내 총 시술 횟수 IVF 시술 횟수 DI 시술 횟수 총 임신 횟수 IVF 임신 횟수 DI 임신 횟수 총 출산 횟수 IVF 출산 횟수 DI 출산 횟수      총 생성 배아 수     미세주입된 난자 수  미세주입에서 생성된 배아 수       이식된 배아 수   미세주입 배아 이식 수       저장된 배아 수  미세주입 후 저장된 배아 수       해동된 배아 수        해동 난자 수    수집된 신선 난자 수    저장된 신선 난자 수       혼합된 난자 수  파트너 정자와 혼합된 난자 수  기증자 정자와 혼합된 난자 수   난자 출처   정자 출처 난자 기증자 나이 정자 기증자 나이    동결 배아 사용 여부    신선 배아 사용 여부    기증 배아 사용 여부         대리모 여부  PGD 시술 여부  PGS 시술 여부  난자 채취 경과일    난자 해동 경과일      난자 혼합 경과일      배아 이식 경과일     배아 해동 경과일       임신 성공 여부
count         256351   256351   256351            9370.000000  256351   256349  256351.000000      256351  250060.000000            2718.0     250060.000000  256351.000000  256351.000000  256351.000000  256351.000000  256351.000000  256351.000000  256351.000000  256351.000000  256351.000000  256351.000000       256351.0    256351.000000  256351.000000  256351.000000       256351.000000   256351.000000  256351.000000      250060  256351        256351    256351   256351  256351    256351   256351  256351    256351   256351  250060.000000  250060.000000     250060.00000  250060.000000  250060.000000  250060.000000    250060.000000  250060.000000  250060.000000  250060.000000  250060.000000  250060.000000     250060.000000     250060.000000  256351  256351    256351    256351  250060.000000  250060.000000  250060.000000  250060.000000     2179.0     1929.0   198863.0  1436.000000  202616.000000  212785.000000  40369.000000  256351.000000
unique        256351        7        7                    NaN       2       24            NaN           4            NaN               NaN               NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN              NaN            NaN            NaN                 NaN             NaN            NaN          13       7             7         7        7       7         7        6       7         6        5            NaN            NaN              NaN            NaN            NaN            NaN              NaN            NaN            NaN            NaN            NaN            NaN               NaN               NaN       3       4         5         7            NaN            NaN            NaN            NaN        NaN        NaN        NaN          NaN            NaN            NaN           NaN            NaN
top     TRAIN_000000   TRDQAZ  만18-34세                    NaN     IVF     ICSI            NaN  기록되지 않은 시행            NaN               NaN               NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN              NaN            NaN            NaN                 NaN             NaN            NaN      현재 시술용      0회            0회        0회       0회      0회        0회       0회      0회        0회       0회            NaN            NaN              NaN            NaN            NaN            NaN              NaN            NaN            NaN            NaN            NaN            NaN               NaN               NaN   본인 제공  배우자 제공    알 수 없음    알 수 없음            NaN            NaN            NaN            NaN        NaN        NaN        NaN          NaN            NaN            NaN           NaN            NaN
freq               1    38969   102476                    NaN  250060   122368            NaN      194432            NaN               NaN               NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN            NaN              NaN            NaN            NaN                 NaN             NaN            NaN      233732   97599        121675    103934   242464  205426    208292   253302  218555    220831   254009            NaN            NaN              NaN            NaN            NaN            NaN              NaN            NaN            NaN            NaN            NaN            NaN               NaN               NaN  234291  229199    242381    230518            NaN            NaN            NaN            NaN        NaN        NaN        NaN          NaN            NaN            NaN           NaN            NaN
mean             NaN      NaN      NaN               9.270651     NaN      NaN       0.771286         NaN       0.233476               1.0          0.012781       0.028516       0.013115       0.030724       0.012432       0.033068       0.008765       0.250730       0.138704       0.372403       0.130392            0.0         0.000039       0.071394       0.001077            0.000004        0.000378       0.000558         NaN     NaN           NaN       NaN      NaN     NaN       NaN      NaN     NaN       NaN      NaN       5.061145       4.170799          2.84365       1.368156       0.724718       1.185975         0.612933       0.454571       0.046401       8.563717       0.093418       7.698928          7.107326          0.534728     NaN     NaN       NaN       NaN       0.160465       0.840342       0.009830       0.004195        1.0        1.0        0.0     0.001393       0.005385       3.254741      0.045629       0.258349
std              NaN      NaN      NaN               3.550313     NaN      NaN       0.420005         NaN       0.423043               0.0          0.112328       0.166441       0.113767       0.172568       0.110805       0.178814       0.093212       0.433434       0.345638       0.483446       0.336734            0.0         0.006246       0.257483       0.032795            0.001975        0.019449       0.023612         NaN     NaN           NaN       NaN      NaN     NaN       NaN      NaN     NaN       NaN      NaN       4.664337       5.625943          4.09464       0.771961       0.894352       2.502318         1.842522       1.415320       0.688246       7.317230       1.105882       6.451914          6.532466          2.509487     NaN     NaN       NaN       NaN       0.367038       0.366289       0.098656       0.064633        0.0        0.0        0.0     0.037307       0.111504       1.715697      0.418672       0.437728
min              NaN      NaN      NaN               0.000000     NaN      NaN       0.000000         NaN       0.000000               1.0          0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000            0.0         0.000000       0.000000       0.000000            0.000000        0.000000       0.000000         NaN     NaN           NaN       NaN      NaN     NaN       NaN      NaN     NaN       NaN      NaN       0.000000       0.000000          0.00000       0.000000       0.000000       0.000000         0.000000       0.000000       0.000000       0.000000       0.000000       0.000000          0.000000          0.000000     NaN     NaN       NaN       NaN       0.000000       0.000000       0.000000       0.000000        1.0        1.0        0.0     0.000000       0.000000       0.000000      0.000000       0.000000
25%              NaN      NaN      NaN               7.000000     NaN      NaN       1.000000         NaN       0.000000               1.0          0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000            0.0         0.000000       0.000000       0.000000            0.000000        0.000000       0.000000         NaN     NaN           NaN       NaN      NaN     NaN       NaN      NaN     NaN       NaN      NaN       1.000000       0.000000          0.00000       1.000000       0.000000       0.000000         0.000000       0.000000       0.000000       2.000000       0.000000       3.000000          0.000000          0.000000     NaN     NaN       NaN       NaN       0.000000       1.000000       0.000000       0.000000        1.0        1.0        0.0     0.000000       0.000000       2.000000      0.000000       0.000000
50%              NaN      NaN      NaN               9.000000     NaN      NaN       1.000000         NaN       0.000000               1.0          0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000            0.0         0.000000       0.000000       0.000000            0.000000        0.000000       0.000000         NaN     NaN           NaN       NaN      NaN     NaN       NaN      NaN     NaN       NaN      NaN       4.000000       0.000000          0.00000       1.000000       0.000000       0.000000         0.000000       0.000000       0.000000       8.000000       0.000000       7.000000          6.000000          0.000000     NaN     NaN       NaN       NaN       0.000000       1.000000       0.000000       0.000000        1.0        1.0        0.0     0.000000       0.000000       3.000000      0.000000       0.000000
75%              NaN      NaN      NaN              11.000000     NaN      NaN       1.000000         NaN       0.000000               1.0          0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       0.000000       1.000000       0.000000       1.000000       0.000000            0.0         0.000000       0.000000       0.000000            0.000000        0.000000       0.000000         NaN     NaN           NaN       NaN      NaN     NaN       NaN      NaN     NaN       NaN      NaN       8.000000       7.000000          5.00000       2.000000       2.000000       2.000000         0.000000       0.000000       0.000000      13.000000       0.000000      11.000000         11.000000          0.000000     NaN     NaN       NaN       NaN       0.000000       1.000000       0.000000       0.000000        1.0        1.0        0.0     0.000000       0.000000       5.000000      0.000000       1.000000
max              NaN      NaN      NaN              20.000000     NaN      NaN       1.000000         NaN       1.000000               1.0          1.000000       1.000000       1.000000       1.000000       1.000000       1.000000       1.000000       1.000000       1.000000       1.000000       1.000000            0.0         1.000000       1.000000       1.000000            1.000000        1.000000       1.000000         NaN     NaN           NaN       NaN      NaN     NaN       NaN      NaN     NaN       NaN      NaN      51.000000      51.000000         43.00000       3.000000       3.000000      51.000000        51.000000      32.000000      36.000000      51.000000      51.000000      51.000000         51.000000         50.000000     NaN     NaN       NaN       NaN       1.000000       1.000000       1.000000       1.000000        1.0        1.0        0.0     1.000000       7.000000       7.000000      7.000000       1.000000